highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://ahmadbinbilal.github.io"  # Sitemap base URL.
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed