highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
environment: prod
url: "http://ahmadbinbilal.github.io"  # Sitemap base URL.
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-feed